"""add_user_role_openid_nickname_isactive_practice_updatedat

Revision ID: 79fc43444ec6
Revises: dc329c3d0a9b
Create Date: 2026-03-21 18:24:09.835200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fc43444ec6'
down_revision: Union[str, None] = 'dc329c3d0a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('openid', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'openid')
    op.drop_column('users', 'role')
    op.drop_column('practices', 'updated_at')
    # ### end Alembic commands ###
