"""initial tables: users, practices, evaluation_history

Revision ID: dc329c3d0a9b
Revises: 
Create Date: 2026-03-21 17:10:57.461333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc329c3d0a9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practices_category'), 'practices', ['category'], unique=False)
    op.create_index(op.f('ix_practices_difficulty'), 'practices', ['difficulty'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('evaluation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.String(length=50), nullable=True),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('recognized_text', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=False),
    sa.Column('fluency', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('word_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_history_practice_id'), 'evaluation_history', ['practice_id'], unique=False)
    op.create_index(op.f('ix_evaluation_history_user_id'), 'evaluation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_history_user_id'), table_name='evaluation_history')
    op.drop_index(op.f('ix_evaluation_history_practice_id'), table_name='evaluation_history')
    op.drop_table('evaluation_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_practices_difficulty'), table_name='practices')
    op.drop_index(op.f('ix_practices_category'), table_name='practices')
    op.drop_table('practices')
    # ### end Alembic commands ###
